export type ChangeKind = "new" | "fix" | "improved" | "soon";
export type ChangeEntry = { date: string; kind: ChangeKind; title: string; detail?: string };

export const CHANGELOG: ChangeEntry[] = [
  { date: "2026-06-03", kind: "new", title: "Live Sports expansion", detail: "NBA, NFL, MLB, NHL, F1, UFC and Tennis tabs with live scores, upcoming fixtures and final results — powered by ESPN's public feed." },
  { date: "2026-06-03", kind: "improved", title: "Radio & Podcasts moved to Home tabs", detail: "Find them alongside CCTV — sticky players, mobile-first layout, and a more reliable podcast feed loader." },
  { date: "2026-06-03", kind: "fix", title: "Podcasts playback", detail: "Rewrote the episode player with proper Audio lifecycle, multi-proxy RSS fallback and per-episode play/pause." },
  { date: "2026-06-02", kind: "new", title: "Radio worldwide", detail: "Stream thousands of free radio stations from anywhere — sticky player keeps playing while you browse." },
  { date: "2026-06-02", kind: "new", title: "Podcasts", detail: "Search, browse and play podcasts. Episodes pulled from public iTunes / RSS feeds." },
  { date: "2026-06-02", kind: "new", title: "Speed test in menu", detail: "Quick built-in internet speed test using Cloudflare's public endpoint." },
  { date: "2026-06-02", kind: "new", title: "Download the app", detail: "Install LaCzek Stream as a PWA or grab the Android APK from the menu." },
  { date: "2026-06-02", kind: "new", title: "Updates channel", detail: "Quick link to the LaCzek Telegram channel for live announcements." },
  { date: "2026-06-02", kind: "improved", title: "Renamed Football tab → Live Sports", detail: "Groundwork for upcoming NBA, NFL, F1, UFC, tennis and more." },
  { date: "—", kind: "soon", title: "Actors & Cast system", detail: "Full /actor/:id pages, cast carousels, actor search, trending actors via TMDB." },
  { date: "—", kind: "soon", title: "AI Developer Agent", detail: "Hidden admin dashboard with log scanner, AI chat and patch previews." },
  { date: "—", kind: "soon", title: "Play-by-play stadium view", detail: "Real-time pitch visualization with events, attack direction & momentum." },
  { date: "—", kind: "soon", title: "Featured events CMS & feature toggles", detail: "Admin can highlight matches/movies and enable/disable features instantly." },
  { date: "—", kind: "soon", title: "Kids profile & parental controls" },
  { date: "—", kind: "soon", title: "Recaps, autoplay next, mobile fill mode, PiP" },
  { date: "2026-05-05", kind: "new", title: "DEV OPTIONS panel", detail: "Real-time visitor analytics with country, time spent, current page and watch history — auto-refreshes every 5 seconds." },
  { date: "2026-05-05", kind: "new", title: "Slide-in navigation drawer", detail: "Cleaner, faster menu that slides in from the right." },
  { date: "2026-05-05", kind: "new", title: "Language selector", detail: "Pick from 70+ languages." },
  { date: "2026-05-05", kind: "new", title: "Live football search", detail: "Find a stream by team or league." },
  { date: "2026-05-05", kind: "new", title: "What's New page", detail: "See everything that ships." },
  { date: "2026-05-05", kind: "improved", title: "Auto-switch broken servers", detail: "If a stream doesn't start within 30s, the next server is loaded automatically." },
  { date: "2026-05-05", kind: "fix", title: "Visitor tracking now works", detail: "All sessions, page views and searches are saved in the cloud." },
  { date: "2026-05-04", kind: "new", title: "Silent ad / popup blocker", detail: "Direct-link redirects from streams are blocked transparently." },
  { date: "2026-05-03", kind: "new", title: "Live match chat", detail: "Real-time chat panel inside every football live stream." },
  { date: "2026-05-02", kind: "fix", title: "Football streams audio restored" },
  { date: "2026-05-02", kind: "improved", title: "Notify-me for upcoming matches" },
  { date: "—", kind: "soon", title: "Full UI translations", detail: "Wiring the language picker into every label." },
  { date: "—", kind: "soon", title: "User accounts & cloud watchlist", detail: "Sync your library across devices." },
  { date: "—", kind: "soon", title: "PiP & Cast support" },
];