/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FootballStreamMatchIdRouteImport } from './routes/football-stream.$matchId'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'
import { Route as WatchKindIdRouteImport } from './routes/watch.$kind.$id'
import { Route as ApiPublicFootballStreamsRouteImport } from './routes/api.public.football-streams'
import { Route as ApiPublicCctvCamerasRouteImport } from './routes/api.public.cctv-cameras'
import { Route as ApiPublicAnimeVideoRouteImport } from './routes/api.public.anime-video'
import { Route as ApiPublicAnimeProxyRouteImport } from './routes/api.public.anime-proxy'
import { Route as ApiPublicAnimeImageRouteImport } from './routes/api.public.anime-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballStreamMatchIdRoute = FootballStreamMatchIdRouteImport.update({
  id: '/football-stream/$matchId',
  path: '/football-stream/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchKindIdRoute = WatchKindIdRouteImport.update({
  id: '/watch/$kind/$id',
  path: '/watch/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballStreamsRoute =
  ApiPublicFootballStreamsRouteImport.update({
    id: '/api/public/football-streams',
    path: '/api/public/football-streams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCctvCamerasRoute = ApiPublicCctvCamerasRouteImport.update({
  id: '/api/public/cctv-cameras',
  path: '/api/public/cctv-cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeVideoRoute = ApiPublicAnimeVideoRouteImport.update({
  id: '/api/public/anime-video',
  path: '/api/public/anime-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeProxyRoute = ApiPublicAnimeProxyRouteImport.update({
  id: '/api/public/anime-proxy',
  path: '/api/public/anime-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnimeImageRoute = ApiPublicAnimeImageRouteImport.update({
  id: '/api/public/anime-image',
  path: '/api/public/anime-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
  '/api/public/anime-image': typeof ApiPublicAnimeImageRoute
  '/api/public/anime-proxy': typeof ApiPublicAnimeProxyRoute
  '/api/public/anime-video': typeof ApiPublicAnimeVideoRoute
  '/api/public/cctv-cameras': typeof ApiPublicCctvCamerasRoute
  '/api/public/football-streams': typeof ApiPublicFootballStreamsRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/football-streams'
    | '/watch/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/football-streams'
    | '/watch/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/anime/$animeId'
    | '/football-stream/$matchId'
    | '/api/public/anime-image'
    | '/api/public/anime-proxy'
    | '/api/public/anime-video'
    | '/api/public/cctv-cameras'
    | '/api/public/football-streams'
    | '/watch/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  FootballStreamMatchIdRoute: typeof FootballStreamMatchIdRoute
  ApiPublicAnimeImageRoute: typeof ApiPublicAnimeImageRoute
  ApiPublicAnimeProxyRoute: typeof ApiPublicAnimeProxyRoute
  ApiPublicAnimeVideoRoute: typeof ApiPublicAnimeVideoRoute
  ApiPublicCctvCamerasRoute: typeof ApiPublicCctvCamerasRoute
  ApiPublicFootballStreamsRoute: typeof ApiPublicFootballStreamsRoute
  WatchKindIdRoute: typeof WatchKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football-stream/$matchId': {
      id: '/football-stream/$matchId'
      path: '/football-stream/$matchId'
      fullPath: '/football-stream/$matchId'
      preLoaderRoute: typeof FootballStreamMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$kind/$id': {
      id: '/watch/$kind/$id'
      path: '/watch/$kind/$id'
      fullPath: '/watch/$kind/$id'
      preLoaderRoute: typeof WatchKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-streams': {
      id: '/api/public/football-streams'
      path: '/api/public/football-streams'
      fullPath: '/api/public/football-streams'
      preLoaderRoute: typeof ApiPublicFootballStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cctv-cameras': {
      id: '/api/public/cctv-cameras'
      path: '/api/public/cctv-cameras'
      fullPath: '/api/public/cctv-cameras'
      preLoaderRoute: typeof ApiPublicCctvCamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-video': {
      id: '/api/public/anime-video'
      path: '/api/public/anime-video'
      fullPath: '/api/public/anime-video'
      preLoaderRoute: typeof ApiPublicAnimeVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-proxy': {
      id: '/api/public/anime-proxy'
      path: '/api/public/anime-proxy'
      fullPath: '/api/public/anime-proxy'
      preLoaderRoute: typeof ApiPublicAnimeProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anime-image': {
      id: '/api/public/anime-image'
      path: '/api/public/anime-image'
      fullPath: '/api/public/anime-image'
      preLoaderRoute: typeof ApiPublicAnimeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  FootballStreamMatchIdRoute: FootballStreamMatchIdRoute,
  ApiPublicAnimeImageRoute: ApiPublicAnimeImageRoute,
  ApiPublicAnimeProxyRoute: ApiPublicAnimeProxyRoute,
  ApiPublicAnimeVideoRoute: ApiPublicAnimeVideoRoute,
  ApiPublicCctvCamerasRoute: ApiPublicCctvCamerasRoute,
  ApiPublicFootballStreamsRoute: ApiPublicFootballStreamsRoute,
  WatchKindIdRoute: WatchKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
