/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FootballStreamMatchIdRouteImport } from './routes/football-stream.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballStreamMatchIdRoute = FootballStreamMatchIdRouteImport.update({
  id: '/football-stream/$matchId',
  path: '/football-stream/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/football-stream/$matchId': typeof FootballStreamMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/football-stream/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/football-stream/$matchId'
  id: '__root__' | '/' | '/football-stream/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FootballStreamMatchIdRoute: typeof FootballStreamMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football-stream/$matchId': {
      id: '/football-stream/$matchId'
      path: '/football-stream/$matchId'
      fullPath: '/football-stream/$matchId'
      preLoaderRoute: typeof FootballStreamMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FootballStreamMatchIdRoute: FootballStreamMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
